# Generated by Django 4.2.17 on 2024-12-15 13:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_section_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
