# Generated by Django 4.2.17 on 2024-12-15 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
