# Generated by Django 4.2.17 on 2024-12-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_settings_setting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setting',
            new_name='Settings',
        ),
    ]
